Repository newrelic/nri-mysql, pull requests merged in 2018-11, with the labels that each got.

#12 Allow old passwords
  src/mysql.go
  src/mysql_test.go
Labels: risk:low

#11 SDK upgraded to v3
  .gitignore
  src/database.go
  src/metrics-parse.go
  src/metrics.go
  src/mysql.go
  src/mysql_test.go
  vendor/github.com/newrelic/infra-integrations-sdk/LICENSE
  vendor/github.com/newrelic/infra-integrations-sdk/args/args.go
  vendor/github.com/newrelic/infra-integrations-sdk/args/json.go
  vendor/github.com/newrelic/infra-integrations-sdk/data/event/event.go
  vendor/github.com/newrelic/infra-integrations-sdk/data/inventory/inventory.go
  vendor/github.com/newrelic/infra-integrations-sdk/data/metric/metrics.go
  vendor/github.com/newrelic/infra-integrations-sdk/data/metric/set_marshal.go
  vendor/github.com/newrelic/infra-integrations-sdk/data/metric/source_type.go
  vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go
  vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go
  vendor/github.com/newrelic/infra-integrations-sdk/integration/options.go
  vendor/github.com/newrelic/infra-integrations-sdk/log/log.go
  vendor/github.com/newrelic/infra-integrations-sdk/persist/storer.go
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
  vendor/gopkg.in/newrelic/infra-integrations-sdk.v2/cache/cache.go
  vendor/gopkg.in/newrelic/infra-integrations-sdk.v2/cache/global.go
  vendor/gopkg.in/newrelic/infra-integrations-sdk.v2/log/log.go
  vendor/gopkg.in/newrelic/infra-integrations-sdk.v2/metric/metrics.go
  vendor/gopkg.in/newrelic/infra-integrations-sdk.v2/sdk/data.go
  vendor/vendor.json
Labels: enhancement, risk:medium

#14 Fix rate and deltas
  CHANGELOG.md
  src/mysql.go
Labels: bug, risk:low

#13 [IHOST-177] Do not return metrics when only INVENTORY flag provided
  CHANGELOG.md
  src/mysql.go
Labels: bug, risk:low
