Repository newrelic/nri-mysql, pull requests merged in 2019-02, with the labels that each got.

#21 Add testify as a dependency
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/newrelic/infra-integrations-sdk/args/args.go
  vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go
  vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/objx/Gopkg.lock
  vendor/github.com/stretchr/objx/Gopkg.toml
  vendor/github.com/stretchr/objx/LICENSE
  vendor/github.com/stretchr/objx/README.md
  vendor/github.com/stretchr/objx/Taskfile.yml
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/objx/conversions.go
  vendor/github.com/stretchr/objx/doc.go
  vendor/github.com/stretchr/objx/map.go
  vendor/github.com/stretchr/objx/mutations.go
  vendor/github.com/stretchr/objx/security.go
  vendor/github.com/stretchr/objx/tests.go
  vendor/github.com/stretchr/objx/type_specific.go
  vendor/github.com/stretchr/objx/type_specific_codegen.go
  vendor/github.com/stretchr/objx/value.go
  vendor/github.com/stretchr/testify/Gopkg.lock
  vendor/github.com/stretchr/testify/Gopkg.toml
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/README.md
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/doc.go
  vendor/github.com/stretchr/testify/go.mod
  vendor/github.com/stretchr/testify/go.sum
  vendor/github.com/stretchr/testify/http/doc.go
  vendor/github.com/stretchr/testify/http/test_response_writer.go
  vendor/github.com/stretchr/testify/http/test_round_tripper.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/vendor.json
Labels: risk:none

#20 Updated to SDK v3.1
  vendor/github.com/newrelic/infra-integrations-sdk/args/args.go
  vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go
  vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go
  vendor/vendor.json
Labels: enhancement, risk:low

#25 Travis integration
  .travis.yml
Labels: risk:none

#22 Dockerized integration tests
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  go.mod
  go.sum
  mysql-definition.yml
  src/mysql.go
  tests/integration/Dockerfile
  tests/integration/docker-compose.yml
  tests/integration/helpers/helpers.go
  tests/integration/integration_test.go
  tests/integration/json-schema-files/mysql-schema-inventory-master.json
  tests/integration/json-schema-files/mysql-schema-master.json
  tests/integration/json-schema-files/mysql-schema-metrics-master.json
  tests/integration/jsonschema/jsonschema.go
  vendor/github.com/bitly/go-simplejson/LICENSE
  vendor/github.com/bitly/go-simplejson/README.md
  vendor/github.com/bitly/go-simplejson/simplejson.go
  vendor/github.com/bitly/go-simplejson/simplejson_go10.go
  vendor/github.com/bitly/go-simplejson/simplejson_go11.go
  vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonpointer/README.md
  vendor/github.com/xeipuuv/gojsonpointer/pointer.go
  vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonreference/README.md
  vendor/github.com/xeipuuv/gojsonreference/reference.go
  vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonschema/README.md
  vendor/github.com/xeipuuv/gojsonschema/draft.go
  vendor/github.com/xeipuuv/gojsonschema/errors.go
  vendor/github.com/xeipuuv/gojsonschema/format_checkers.go
  vendor/github.com/xeipuuv/gojsonschema/glide.yaml
  vendor/github.com/xeipuuv/gojsonschema/internalLog.go
  vendor/github.com/xeipuuv/gojsonschema/jsonContext.go
  vendor/github.com/xeipuuv/gojsonschema/jsonLoader.go
  vendor/github.com/xeipuuv/gojsonschema/locales.go
  vendor/github.com/xeipuuv/gojsonschema/result.go
  vendor/github.com/xeipuuv/gojsonschema/schema.go
  vendor/github.com/xeipuuv/gojsonschema/schemaLoader.go
  vendor/github.com/xeipuuv/gojsonschema/schemaPool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaReferencePool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaType.go
  vendor/github.com/xeipuuv/gojsonschema/subSchema.go
  vendor/github.com/xeipuuv/gojsonschema/types.go
  vendor/github.com/xeipuuv/gojsonschema/utils.go
  vendor/github.com/xeipuuv/gojsonschema/validation.go
  vendor/vendor.json
Labels: risk:none

#24 Add suffix for selecting yml while packaging
  Makefile-package.mk
Labels: bug

#27 Add spec files
  spec.csv
  spec.inventory.csv
Labels: risk:none
